layout:"fit",
id: 'web-radio',
title:'Radios',
maximizable: false,
resizable: false,
width:365,
height:322,
iconCls: 'tabs',
shim:false,
tbar: this.northToolbar,
plugins: new Ext.ux.FlashPlugin(),
swf: ,//layout:"fit",
id: 'web-radio',
title:'Radios',
maximizable: false,
resizable: false,
width:365,
height:322,
iconCls: 'tabs',
shim:false,
tbar: this.northToolbar,
plugins: new Ext.ux.FlashPlugin(),
swf: 'swf/example.swf' , //'B@1930359[B@c0cdfe[B@141052[B@13b80c3[B@182b51a'(want to read)
flashvars: {csConfigFile: 'swf/x_config.xml',
csColor:'FFFFFF',
csPreload:x_preload.swf',
chartHeight: function() {return this.body.getSize().height -5; }, 
chartWidth: function(){ return this.body.getSize().width -5; }, 
csFilesetBookmark: 'args.movie'}
flashvars: {csConfigFile: 'x_config.xml',
csColor:'FFFFFF',
csPreloader:'x_preload.swf',
chartHeight: function() {return this.body.getSize().height -5; }, 
chartWidth: function(){ return this.body.getSize().width -5; }, 
csFilesetBookmark: 'args.movie'}
